### PR TITLE
French translation, first version

### PR DESCRIPTION
**Pull request by j2l**
I translated Editor to French! :slightly_smiling_face: 
Hope it helps.
In the interface, I see some missing labels like "New Artboard", Content, Circle, etc, but it's ok for now. In European languages, we usually translate everything.
Feel free to change to a new branch.

### CODE REVIEW

**Comment by easylogic** [comment]
Wow! Thank you very much! ^^ 

As you say, `New Artboard` hasn't applied translation yet.

It's still coming out in English in Korean. 
It's not a UI, but a drawing object.
So it's configured differently from the UI.

I'm going to think about it and tell you so I can change it.

**Comment by j2l** [comment]
I understand.
Maybe, by replacing the drawing object text with an icon, like an emoji (say 🖼️ from https://emojipedia.org/framed-picture/i or a font awesome icon?

**Comment by j2l** [comment]
BTW, It's not urgent at all.
Translation is to help you reach new audiences. I don't need it to go forward.

Animating SVG points in sync with video and learning how to develop a tool with Sapa are more important to me :smile: 
I think of a first (mixed with video, or pure) SVG short film using Editor (but not in SMIL like  https://codepen.io/guttentag/post/fire-bringer-of-atrani-explained, BTW wonderful [posts](https://codepen.io/guttentag/posts/popular) from this guy), 

And I'd also love to develop (with help) a tool like [Mavo+GrapesJS](https://github.com/mavoweb/create) to prototype any frontend and backend at the same time, with low code (linked fields, offline storage sync to Rest API client) to build PWA easily. My first PWA app is a [French interactive fiction](https://realistis.bitbucket.io/). Seeing Summernote and Sapa, it seems to go in the same way, but I'll need docs and time, and help if possible with Sapa.

I define myself as a transmedia storyteller independent artist.

I already know how to make animated svg with Blender (zipped, github doesn't allow svg):
[cube_dashed_anim.zip](https://github.com/easylogic/editor/files/4785251/cube_dashed_anim.zip)

But it's a frame by frame animation turning this simple animation into 700kB, while video version could be 200kB, I'd like to import some SVG from Blender, then have CSS tween, and morphs. 
Maybe with some frame by frame animations mixed together (very hard I guess).

And since CSS animation is favoured to SMIL, the best option is not Blender for animation.

Don't want to afraid you, just sharing my mind :smile:

**Comment by easylogic** [comment]
Thank you for the good words. 
I wish I could make an app that could help you with something.

**Comment by j2l** [comment]
Thank you so much!
I start with Sapa ASAP.
Do you have some insights to understand how you developed Editor using Sapa, beside commits history of course?
I see a modification to the video layer implies multiple changes in various files. How do you track classes, menus, function, ...
What IDE, layout, process do you use?

**Comment by easylogic** [comment]
Sapa is the basic core for dealing with the UI. In order to control the editor in detail, we need to explain the inside of the editor. It is not ready yet.

**Comment by j2l** [comment]
OK. I will wait then :smile:

**Pull request merged**
